version: "1"

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: expensein
    container_name: expensein
    restart: unless-stopped
    env_file: .env
    environment:
      - ATLAS_URI=$ATLAS_URI
    ports:
      - "80:5000"
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    networks:
      - app-network
    command: /usr/src/app/backend/nodemon server.js
